"""
Unit and Integration Tests for Session-Isolated Subskills & Borrowing Engine (Spec 13)
"""

import os
import shutil
import tempfile
import unittest
from fastapi.testclient import TestClient

from server.models import (
    SubskillModel,
    SubskillsIndexModel,
    BorrowSubskillPayload,
    RegisterSubskillPayload,
    SessionEventType,
)
from server.db import get_connection
from server.session_manager import SessionManager
from server.subskills.manager import SubskillsManager, parse_sop_playbook
from server.socket_server import app, state


class TestSubskillsEngine(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.mkdtemp()
        self.logs_dir = os.path.join(self.temp_dir, "logs")
        os.makedirs(self.logs_dir, exist_ok=True)
        self.manager = SessionManager(base_log_dir=self.logs_dir)
        self.client = TestClient(app)
        self.client.headers.update({"X-AgentSocket-Token": state.server_token})
        state.global_permissions["enable_subskills"] = True

    def tearDown(self):
        shutil.rmtree(self.temp_dir, ignore_errors=True)

    def test_session_folder_structure(self):
        """Verify active session automatically creates input/, output/, adhocs/, artifacts/ folders."""
        session = self.manager.get_or_create_session(
            tab_group_id=123,
            tab_group_name="Test Subskills Group",
            agent_name="TestAgent"
        )
        self.assertTrue(os.path.isdir(session.input_dir))
        self.assertTrue(os.path.isdir(session.output_dir))
        self.assertFalse(os.path.exists(session.adhocs_dir))  # Spec 25: adhocs/ not generated by default
        self.assertTrue(os.path.isdir(session.artifacts_dir))

        paths = self.manager.get_session_paths(session.session_id)
        self.assertEqual(paths["input_dir"], session.input_dir)
        self.assertEqual(paths["output_dir"], session.output_dir)
        self.assertEqual(paths["adhocs_dir"], session.adhocs_dir)
        self.assertEqual(paths["artifacts_dir"], session.artifacts_dir)

    def test_register_and_list_subskills(self):
        """Verify subskill registration, indexing, search, and tag filtering."""
        # Create a mock source session
        session = self.manager.get_or_create_session(
            tab_group_id=200,
            tab_group_name="Source CRM Run",
            agent_name="TestAgent"
        )
        # Create sub_skill.md and an adhoc script in source
        playbook_content = """---
name: test-crm-enricher
display_title: "Test CRM Profile Enricher"
description: "Tested playbook for CRM enrichment."
tags: ["crm", "enrichment", "test"]
---
# CRM Playbook
Test instructions.
"""
        with open(os.path.join(session.session_dir, "sub_skill.md"), "w", encoding="utf-8") as f:
            f.write(playbook_content)

        os.makedirs(session.adhocs_dir, exist_ok=True)
        with open(os.path.join(session.adhocs_dir, "extract_tool.py"), "w", encoding="utf-8") as f:
            f.write("# Extract helper tool\nprint('extracted')\n")

        # Register subskill
        reg_res = self.manager.register_subskill(
            session_path=session.session_dir,
            name="test-crm-enricher",
            display_title="Test CRM Profile Enricher",
            description="Tested playbook for CRM enrichment.",
            tags=["crm", "enrichment", "test"],
            adhoc_tools=["extract_tool.py"]
        )
        self.assertEqual(reg_res["status"], "success")

        # List subskills
        all_skills = self.manager.list_subskills()
        self.assertEqual(len(all_skills), 1)
        self.assertEqual(all_skills[0]["name"], "test-crm-enricher")

        # Query filter
        match = self.manager.list_subskills(query="CRM")
        self.assertEqual(len(match), 1)
        no_match = self.manager.list_subskills(query="nonexistent")
        self.assertEqual(len(no_match), 0)

        # Tag filter
        tag_match = self.manager.list_subskills(tags=["enrichment"])
        self.assertEqual(len(tag_match), 1)
        tag_no_match = self.manager.list_subskills(tags=["finance"])
        self.assertEqual(len(tag_no_match), 0)

    def test_get_subskill_details(self):
        """Verify retrieving full subskill details and playbook content."""
        session = self.manager.get_or_create_session(tab_group_id=300, tab_group_name="Playbook Run")
        with open(os.path.join(session.session_dir, "sub_skill.md"), "w", encoding="utf-8") as f:
            f.write("# Custom Subskill Playbook Content\n\nSelectors: `.custom-btn`")

        self.manager.register_subskill(
            session_path=session.session_dir,
            name="custom-scraper",
            display_title="Custom Scraper",
            description="Extracts data from custom pages.",
            tags=["scraper"]
        )

        details = self.manager.get_subskill("custom-scraper")
        self.assertIsNotNone(details)
        self.assertEqual(details["name"], "custom-scraper")
        self.assertIn("Custom Subskill Playbook Content", details["playbook_markdown"])

    def test_borrow_subskill_workflow(self):
        """Verify complete borrowing lifecycle: playbook copy, adhocs copy, input copy, event logging."""
        # 1. Setup source session
        src_session = self.manager.get_or_create_session(tab_group_id=400, tab_group_name="Source Session")
        with open(os.path.join(src_session.session_dir, "sub_skill.md"), "w", encoding="utf-8") as f:
            f.write("# Source Playbook Content")
        os.makedirs(src_session.adhocs_dir, exist_ok=True)
        with open(os.path.join(src_session.adhocs_dir, "probe_dom.py"), "w", encoding="utf-8") as f:
            f.write("# DOM Probe script\n")

        self.manager.register_subskill(
            session_path=src_session.session_dir,
            name="borrow-target-skill",
            display_title="Borrow Target Skill",
            tags=["borrow"]
        )

        # 2. Prepare sample input file to pass during borrow
        sample_input = os.path.join(self.temp_dir, "sample_input.csv")
        with open(sample_input, "w", encoding="utf-8") as f:
            f.write("id,url\n1,https://example.com/user1\n")

        # 3. Borrow subskill into a new session
        borrow_res = self.manager.borrow_subskill(
            name="borrow-target-skill",
            target_session_id_or_title_or_path="Batch 2 Run",
            tab_group_id=500,
            input_file_path=sample_input
        )
        self.assertEqual(borrow_res["status"], "success")
        target_dir = borrow_res["target_session_dir"]

        # Check copied files: sub_skill.md and SESSION_DOCUMENT.md exist, tools remain referenced (Spec 18 & 25)
        self.assertTrue(os.path.exists(os.path.join(target_dir, "sub_skill.md")))
        self.assertTrue(os.path.exists(os.path.join(target_dir, "SESSION_DOCUMENT.md")))
        manifest = self.manager.storage.read_manifest(target_dir)
        self.assertTrue(any(b.name == "borrow-target-skill" for b in manifest.borrowed_subskills))
        # Lean staging: tools are referenced, not physically duplicated into target adhocs/
        self.assertFalse(os.path.exists(os.path.join(target_dir, "adhocs", "probe_dom.py")))
        self.assertTrue(os.path.exists(os.path.join(target_dir, "input", "sample_input.csv")))
        self.assertTrue(os.path.exists(os.path.join(target_dir, "SESSION_DOCUMENT.md")))

        # Check hierarchical resolution resolves probe_dom.py via subskill tier
        resolved = self.manager.resolve_adhoc("probe_dom.py", target_dir)
        self.assertTrue(resolved["found"])
        self.assertEqual(resolved["tier"], "subskill")

        # Check borrow counter incremented in index
        details = self.manager.get_subskill("borrow-target-skill")
        self.assertEqual(details["times_borrowed"], 1)

        # Check subskill_borrowed event logged in target session.jsonl
        sess_details = self.manager.get_session_details(target_dir)
        events = sess_details["events"]
        borrow_events = [e for e in events if e.get("type") == SessionEventType.SUBSKILL_BORROWED.value]
        self.assertEqual(len(borrow_events), 1)
        self.assertEqual(borrow_events[0]["payload"]["subskill_name"], "borrow-target-skill")

    def test_session_document_and_alias(self):
        """Verify SESSION_DOCUMENT.md generation and section completeness."""
        session = self.manager.get_or_create_session(tab_group_id=600, tab_group_name="Document Test Run")

        with open(os.path.join(session.input_dir, "data_in.csv"), "w", encoding="utf-8") as f:
            f.write("col1,col2\nval1,val2\n")

        with open(os.path.join(session.output_dir, "results.csv"), "w", encoding="utf-8") as f:
            f.write("col1,col2,enriched\nval1,val2,yes\n")

        os.makedirs(session.adhocs_dir, exist_ok=True)
        with open(os.path.join(session.adhocs_dir, "helper.py"), "w", encoding="utf-8") as f:
            f.write('"""Helper script docstring."""\n')

        # Finalize session to trigger document generation
        self.manager.finalize_session(session.session_id, end_reason="task_complete")

        doc_path = os.path.join(session.session_dir, "SESSION_DOCUMENT.md")
        self.assertTrue(os.path.exists(doc_path))

        with open(doc_path, "r", encoding="utf-8") as f:
            doc_content = f.read()


        self.assertIn("Session Document: `Document Test Run`", doc_content)
        self.assertIn("data_in.csv", doc_content)
        self.assertIn("results.csv", doc_content)
        self.assertIn("helper.py", doc_content)
        self.assertIn("Helper script docstring.", doc_content)
        self.assertIn("Chronological Execution Timeline Thread", doc_content)

    def test_fastapi_endpoints(self):
        """Verify REST API gateway endpoints for subskills and session documents."""
        # 1. GET /subskills
        resp = self.client.get("/subskills")
        self.assertEqual(resp.status_code, 200)
        self.assertIsInstance(resp.json(), list)

        # 2. GET /subskills/{name} on official reference subskill
        resp = self.client.get("/subskills/linkedin-crm-enricher")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertEqual(data["status"], "success")
        self.assertEqual(data["data"]["name"], "linkedin-crm-enricher")

        # 3. GET /session/document
        ref_path = "server/logs/2026-08-21/LinkedIn_CRM_Enricher_08-45_gid101"
        resp = self.client.get("/session/document", params={"path": ref_path})
        self.assertEqual(resp.status_code, 200)
        doc_json = resp.json()
        self.assertEqual(doc_json["status"], "success")
        self.assertIn("Session Document", doc_json["document_markdown"])

    def test_spec26_sqlite_subskills_table_sync(self):
        """Spec 26: Verify subskills are upserted into SQLite subskills table and JSON export."""
        sess = self.manager.get_or_create_session(tab_group_id=701, tab_group_name="Spec 26 Sync Run")
        playbook_text = """---
name: spec26-lead-sop
display_title: "Spec 26 Lead SOP"
description: "SOP playbook for lead qualification without executable scripts."
tags: ["leads", "qualification", "b2b"]
version: "2.1.0"
---
# Playbook: Spec 26 Lead SOP

## Strategic Objective
Qualify leads using browser observation and atomic actions.

## Recommended OODA Steps
1. Call `browser_observe` to inspect profile card.
2. Determine lead relevance score.
3. If CAPTCHA is detected, wait for human takeover.
"""
        with open(os.path.join(sess.session_dir, "sub_skill.md"), "w", encoding="utf-8") as f:
            f.write(playbook_text)

        reg_res = self.manager.register_subskill(
            session_path=sess.session_dir,
            name="spec26-lead-sop",
            display_title="Spec 26 Lead SOP",
            description="SOP playbook for lead qualification without executable scripts.",
            tags=["leads", "qualification", "b2b"],
        )
        self.assertEqual(reg_res["status"], "success")

        # 1. Verify directly in SQLite subskills table
        with get_connection(self.manager.storage.db_path) as conn:
            cur = conn.execute(
                "SELECT slug, display_title, description, tags, times_referenced, playbook_path FROM subskills WHERE slug = ?",
                ("spec26-lead-sop",),
            )
            row = cur.fetchone()
            self.assertIsNotNone(row)
            self.assertEqual(row["slug"], "spec26-lead-sop")
            self.assertEqual(row["display_title"], "Spec 26 Lead SOP")
            self.assertIn("qualification", row["tags"])
            self.assertTrue(row["playbook_path"].endswith("sub_skill.md"))

        # 2. Verify portable JSON export
        index_model = self.manager._read_subskills_index()
        self.assertEqual(index_model.version, "2.1.0")
        self.assertIn("spec26-lead-sop", index_model.subskills)
        exported = index_model.subskills["spec26-lead-sop"]
        self.assertEqual(exported.display_title, "Spec 26 Lead SOP")
        self.assertTrue(exported.playbook_path.endswith("sub_skill.md"))

    def test_spec26_sop_markdown_playbook_structure(self):
        """Spec 26: Verify example-sop structure and zero executable scripts."""
        example_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "server", "subskills", "example-sop")
        playbook_file = os.path.join(example_dir, "sub_skill.md")
        self.assertTrue(os.path.isfile(playbook_file), "example-sop/sub_skill.md must exist.")

        with open(playbook_file, "r", encoding="utf-8") as f:
            content = f.read()

        # Zero executable scripts: verify no python files in example-sop/
        files_in_folder = os.listdir(example_dir)
        py_files = [f for f in files_in_folder if f.endswith(".py")]
        self.assertEqual(len(py_files), 0, "SOP subskills must contain zero executable scripts.")

        # Verify frontmatter
        fm, body = parse_sop_playbook(content)
        self.assertEqual(fm.get("name"), "example-sop")
        self.assertEqual(fm.get("version"), "2.1.0")

        # Verify OODA structure
        self.assertIn("Strategic Objective", body)
        self.assertIn("Recommended OODA Steps", body)
        self.assertIn("Awaiting Human 2FA", body)

    def test_spec26_sqlite_query_with_json_fallback(self):
        """Spec 26: Verify fast SQLite queries with automatic fallback to subskills_index.json."""
        # Query via manager (hits SQLite)
        results = self.manager.list_subskills()
        self.assertIsInstance(results, list)

        # Retrieve a subskill via get_subskill
        sess = self.manager.get_or_create_session(tab_group_id=801, tab_group_name="Fallback Test")
        with open(os.path.join(sess.session_dir, "sub_skill.md"), "w", encoding="utf-8") as f:
            f.write("# Fallback Playbook\nOODA Step 1: Observe")

        self.manager.register_subskill(
            session_path=sess.session_dir,
            name="fallback-skill",
            display_title="Fallback Test Skill",
            tags=["fallback", "test"],
        )

        # 1. Normal SQLite retrieval
        sk = self.manager.get_subskill("fallback-skill")
        self.assertIsNotNone(sk)
        self.assertEqual(sk["name"], "fallback-skill")
        self.assertIn("Fallback Playbook", sk["playbook_markdown"])

        # 2. Test fallback when SQLite list fails
        orig_list_sqlite = self.manager.subskills.list_subskills_sqlite
        self.manager.subskills.list_subskills_sqlite = lambda query="", tags=None: None
        try:
            fallback_results = self.manager.list_subskills(query="Fallback")
            self.assertEqual(len(fallback_results), 1)
            self.assertEqual(fallback_results[0]["name"], "fallback-skill")
        finally:
            self.manager.subskills.list_subskills_sqlite = orig_list_sqlite

        # 3. Test fallback when SQLite get fails
        orig_get_sqlite = self.manager.subskills.get_subskill_sqlite
        self.manager.subskills.get_subskill_sqlite = lambda name: None
        try:
            fallback_sk = self.manager.get_subskill("fallback-skill")
            self.assertIsNotNone(fallback_sk)
            self.assertEqual(fallback_sk["name"], "fallback-skill")
            self.assertIn("Fallback Playbook", fallback_sk["playbook_markdown"])
        finally:
            self.manager.subskills.get_subskill_sqlite = orig_get_sqlite

    def test_spec26_times_referenced_increment(self):
        """Spec 26: Verify times_referenced is incremented in SQLite and index on borrow."""
        sess = self.manager.get_or_create_session(tab_group_id=901, tab_group_name="Counter Run")
        with open(os.path.join(sess.session_dir, "sub_skill.md"), "w", encoding="utf-8") as f:
            f.write("# Counter Playbook")

        self.manager.register_subskill(
            session_path=sess.session_dir,
            name="counter-skill",
            display_title="Counter Test Skill",
        )

        # Initial times_referenced should be 0
        details = self.manager.get_subskill("counter-skill")
        self.assertEqual(details["times_referenced"], 0)

        # Borrow once
        self.manager.borrow_subskill(
            name="counter-skill",
            target_session_id_or_title_or_path="Target Session A",
            tab_group_id=902,
        )

        # Check in SQLite directly
        with get_connection(self.manager.storage.db_path) as conn:
            cur = conn.execute("SELECT times_referenced FROM subskills WHERE slug = ?", ("counter-skill",))
            row = cur.fetchone()
            self.assertEqual(row["times_referenced"], 1)

        # Check in index JSON
        index_model = self.manager._read_subskills_index()
        self.assertEqual(index_model.subskills["counter-skill"].times_referenced, 1)

        # Borrow second time
        self.manager.borrow_subskill(
            name="counter-skill",
            target_session_id_or_title_or_path="Target Session B",
            tab_group_id=903,
        )

        with get_connection(self.manager.storage.db_path) as conn:
            cur = conn.execute("SELECT times_referenced FROM subskills WHERE slug = ?", ("counter-skill",))
            row = cur.fetchone()
            self.assertEqual(row["times_referenced"], 2)

    def test_spec26_fastapi_example_sop_endpoint(self):
        """Spec 26: Verify FastAPI GET /subskills/example-sop returns markdown OODA playbook."""
        resp = self.client.get("/subskills/example-sop")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertEqual(data["status"], "success")
        self.assertEqual(data["data"]["name"], "example-sop")
        self.assertIn("Recommended OODA Steps", data["data"]["playbook_markdown"])
        self.assertIn("Awaiting Human 2FA", data["data"]["playbook_markdown"])


if __name__ == "__main__":
    unittest.main()
